import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { api } from "../utils/api";
import { getOptions } from "../utils/getChamps";

const Home: NextPage = () => {
  const [ids, setIds] = useState(() => getOptions());

  const [first, second] = ids;
  console.log(first, second);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center px-4 py-16 ">
          <h1 className="pb-12 text-3xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Strongest <span className="text-[hsl(280,100%,70%)]">Champ</span>
          </h1>

          <h2 className="text-2xl text-white">
            Which champ will win a 1 v 1 fight with full build?
          </h2>

          <div className=" flex max-w-2xl items-center justify-end rounded border border-red-50 p-8">
            <div className="h-16 w-16 bg-red-700 text-lg">{first}</div>

            <div className="p-8 text-xl text-white">vs.</div>

            <div className="h-16 w-16 bg-red-700 text-lg">{second}</div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
