/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

import { api } from "../utils/api";
import { getOptions } from "../utils/getChamps";

const imageURL =
  "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zoe_0.jpg";

const Home: NextPage = () => {
  const [ids, setIds] = useState(() => getOptions());

  const [first, second] = ids;
  console.log(first, second);

  const firstChamp = api.champs.getChampByID.useQuery({ id: first });
  const secondChamp = api.champs.getChampByID.useQuery({ id: second });
  console.log(first);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center px-4 py-16 ">
          <h1 className="pb-12 text-3xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Strongest <span className="text-[hsl(280,100%,70%)]">Champ</span>
          </h1>

          <h2 className="text-2xl text-white">
            Which champ will win a 1 v 1 fight with full build?
          </h2>

          <div className=" flex items-center justify-end border border-rose-200 p-8">
            <div className="flex aspect-[5/9] h-80 flex-col bg-red-500">
              <img
                src={firstChamp.data?.image}
                alt={firstChamp.data?.name}
                className="aspect-auto h-full"
              ></img>
              <div className="pt-3 text-center text-white">
                {firstChamp.data?.name}
              </div>
            </div>

            <div className="p-8 text-xl text-white">vs.</div>

            <div className="flex aspect-[5/9] h-80 flex-col">
              <img
                src={secondChamp.data?.image}
                alt={secondChamp.data?.name}
                className="h-full"
              ></img>
              <div className="pt-3 text-center text-white">
                {secondChamp.data?.name}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
